insert into movie (id, name, description, grade, likes) values (1, 'Trash', 'Expanded even-keeled project', 4, 216);
insert into movie (id, name, description, grade, likes) values (2, 'Blood Done Sign My Name', 'Streamlined tangible Graphic Interface', 4, 682);
insert into movie (id, name, description, grade, likes) values (3, 'Sketches of Frank Gehry', 'Configurable optimizing encoding', 3, 2188);
insert into movie (id, name, description, grade, likes) values (4, 'Decoder', 'Streamlined client-server installation', 2, 1346);
insert into movie (id, name, description, grade, likes) values (5, 'Inferno', 'Switchable didactic concept', 4, 465);
insert into movie (id, name, description, grade, likes) values (6, 'Bad Teacher', 'Profound reciprocal hub', 3, 231);
insert into movie (id, name, description, grade, likes) values (7, 'Ward, The', 'Assimilated cohesive access', 4, 1368);
insert into movie (id, name, description, grade, likes) values (8, 'In Vanda''s Room (No Quarto da Vanda)', 'Operative 3rd generation access', 3, 604);
insert into movie (id, name, description, grade, likes) values (9, 'Bobby Jones, Stroke of Genius', 'Mandatory multi-tasking groupware', 4, 1650);
insert into movie (id, name, description, grade, likes) values (10, 'Life as We Know It', 'Persevering 4th generation framework', 5, 101);
insert into movie (id, name, description, grade, likes) values (11, 'Premature', 'Synergistic incremental complexity', 2, 1831);
insert into movie (id, name, description, grade, likes) values (12, 'Vegas Vacation (National Lampoon''s Las Vegas Vacation)', 'Horizontal secondary circuit', 5, 1676);
insert into movie (id, name, description, grade, likes) values (13, 'Timerider: The Adventure of Lyle Swann', 'Front-line tertiary internet solution', 1, 1702);
insert into movie (id, name, description, grade, likes) values (14, 'Cthulhu', 'Digitized multimedia contingency', 1, 1445);
insert into movie (id, name, description, grade, likes) values (15, 'Welcome', 'Realigned neutral definition', 4, 274);
insert into movie (id, name, description, grade, likes) values (16, 'American Hustle', 'Function-based responsive focus group', 1, 668);
insert into movie (id, name, description, grade, likes) values (17, 'Noriko''s Dinner Table (Noriko no shokutaku)', 'Ergonomic client-driven model', 2, 827);
insert into movie (id, name, description, grade, likes) values (18, 'Assault, The (Aanslag, De)', 'Progressive methodical protocol', 1, 1945);
insert into movie (id, name, description, grade, likes) values (19, 'Biggie and Tupac', 'Open-source disintermediate artificial intelligence', 1, 678);
insert into movie (id, name, description, grade, likes) values (20, 'California Dreamin'' (Nesfarsit)', 'Customizable well-modulated time-frame', 3, 1947);
insert into review (id, movie_id, review) values (1, 13, 'User-friendly bifurcated hub');
insert into review (id, movie_id, review) values (2, 18, 'Horizontal next generation attitude');
insert into review (id, movie_id, review) values (3, 16, 'Reverse-engineered coherent database');
insert into review (id, movie_id, review) values (4, 13, 'Team-oriented next generation array');
insert into review (id, movie_id, review) values (5, 20, 'Expanded interactive array');
insert into review (id, movie_id, review) values (6, 1, 'Sharable homogeneous core');
insert into review (id, movie_id, review) values (7, 9, 'Visionary multi-tasking paradigm');
insert into review (id, movie_id, review) values (8, 18, 'Function-based value-added alliance');
insert into review (id, movie_id, review) values (9, 4, 'Cross-platform eco-centric database');
insert into review (id, movie_id, review) values (10, 10, 'Object-based stable attitude');
insert into review (id, movie_id, review) values (11, 8, 'Virtual grid-enabled pricing structure');
insert into review (id, movie_id, review) values (12, 13, 'Fully-configurable motivating hierarchy');
insert into review (id, movie_id, review) values (13, 6, 'Programmable methodical system engine');
insert into review (id, movie_id, review) values (14, 10, 'Programmable multimedia emulation');
insert into review (id, movie_id, review) values (15, 16, 'Ameliorated system-worthy Graphic Interface');
insert into review (id, movie_id, review) values (16, 14, 'Multi-layered clear-thinking structure');
insert into review (id, movie_id, review) values (17, 1, 'Integrated explicit secured line');
insert into review (id, movie_id, review) values (18, 3, 'Open-architected systematic matrices');
insert into review (id, movie_id, review) values (19, 9, 'Future-proofed incremental collaboration');
insert into review (id, movie_id, review) values (20, 20, 'Grass-roots human-resource benchmark');